# Generated by Django 5.0.1 on 2024-03-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_photos/",
                verbose_name="Photo",
            ),
        ),
    ]
