# Generated by Django 5.0.1 on 2024-03-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0003_client_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_deleted",
            field=models.BooleanField(
                default=False,
                help_text="button to toggle employee deleted and undelete",
                verbose_name="Is This Client Deleted ?",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="client_photos/", verbose_name="Photo"
            ),
        ),
    ]
