# Generated by Django 5.0.1 on 2024-02-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0006_leave"),
    ]

    operations = [
        migrations.AddField(
            model_name="leave",
            name="leave_days",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Leave Days"
            ),
            preserve_default=False,
        ),
    ]
