# Generated by Django 5.0.1 on 2024-02-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0033_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="phone",
            field=models.CharField(max_length=125, verbose_name="Phone"),
        ),
    ]
