# Generated by Django 5.0.1 on 2024-03-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0043_leave_is_rejected_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="employee_photos/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
    ]
