# Generated by Django 5.0.1 on 2024-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0048_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("half-day", "Half"),
                    ("absent", "Absent"),
                    ("present", "Present"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
    ]
