# Generated by Django 5.0.1 on 2024-05-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0073_alter_attendanceregister_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half-day', 'Half')], default='absent', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.CharField(default='Emp-001', max_length=125, verbose_name='Employee ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='employee_photos/', verbose_name='Photo'),
        ),
    ]
