# Generated by Django 5.0.1 on 2024-05-23 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0074_alter_attendanceregister_status_and_more'),
        ('employee', '0078_alter_attendanceregister_status'),
    ]

    operations = [
    ]
