# Generated by Django 5.0.1 on 2024-05-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0079_alter_attendanceregister_status'),
        ('employee', '0079_merge_20240523_0627'),
    ]

    operations = [
    ]
