# Generated by Django 5.0.1 on 2024-05-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0080_merge_20240524_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceregister',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half-day', 'Half')], default='absent', max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Photo'),
        ),
    ]
