# Generated by Django 5.0.1 on 2024-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0085_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True, max_length=125, null=True, verbose_name="Gender"
            ),
        ),
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("absent", "Absent"),
                    ("present", "Present"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
    ]
