# Generated by Django 5.0.1 on 2024-05-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0086_employee_gender_alter_attendanceregister_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceregister",
            name="status",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("absent", "Absent"),
                    ("half-day", "Half"),
                ],
                default="absent",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Female", "Female"), ("Male", "Male"), ("Other", "Other")],
                max_length=125,
                null=True,
                verbose_name="Gender",
            ),
        ),
    ]
