# Generated by Django 5.0.1 on 2024-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_company_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="Address"),
        ),
    ]
