# Generated by Django 5.0.1 on 2024-03-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_company_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="mobile",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Mobile Number"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(max_length=128, verbose_name="Phone Number"),
        ),
    ]
