# Generated by Django 5.0.1 on 2024-02-11 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employee", "0007_leave_leave_days"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("auto_id", models.PositiveIntegerField(db_index=True, unique=True)),
                ("a_id", models.PositiveIntegerField()),
                ("date_added", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("date_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "job_title",
                    models.CharField(max_length=125, verbose_name="Job Title"),
                ),
                (
                    "job_location",
                    models.CharField(max_length=125, verbose_name="Job Location"),
                ),
                (
                    "no_of_vacancies",
                    models.CharField(
                        max_length=100, verbose_name="Number Of Vacancies"
                    ),
                ),
                (
                    "experience",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Experience"
                    ),
                ),
                ("Age", models.PositiveIntegerField(verbose_name="Age")),
                (
                    "salary_from",
                    models.PositiveIntegerField(verbose_name="Salary From"),
                ),
                ("salary_to", models.PositiveIntegerField(verbose_name="Salary To")),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("Full Time", "Full Time"),
                            ("Part Time", "Part time"),
                            ("Internship", "Internship"),
                            ("Contract", "Contract"),
                        ],
                        default="Additions",
                        max_length=128,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Open", "Open"), ("Close", "Close")],
                        default="Additions",
                        max_length=128,
                    ),
                ),
                (
                    "start_date",
                    models.DateField(help_text="start date", verbose_name="Start Date"),
                ),
                (
                    "expired_date",
                    models.DateField(
                        help_text="expired date", verbose_name="Expired Date"
                    ),
                ),
                ("description", models.CharField(max_length=254)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.company",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="creator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        limit_choices_to={"is_deleted": False},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.department",
                    ),
                ),
                (
                    "updator",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="updator_%(class)s_objects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["job_title"],
            },
        ),
    ]
