# Generated by Django 5.0.1 on 2024-03-14 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0046_alter_attendanceregister_status"),
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="Age",
            field=models.PositiveIntegerField(null=True, verbose_name="Age"),
        ),
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.ForeignKey(
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="expired_date",
            field=models.DateField(
                help_text="expired date", null=True, verbose_name="Expired Date"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_location",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Job Location"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_title",
            field=models.CharField(max_length=255, verbose_name="Job Title"),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Full Time", "Full Time"),
                    ("Part Time", "Part time"),
                    ("Internship", "Internship"),
                    ("Contract", "Contract"),
                ],
                default="Full Time",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="no_of_vacancies",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Number Of Vacancies"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_from",
            field=models.PositiveIntegerField(null=True, verbose_name="Salary From"),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_to",
            field=models.PositiveIntegerField(null=True, verbose_name="Salary To"),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateField(
                help_text="start date", null=True, verbose_name="Start Date"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Close", "Close")],
                default="Open",
                max_length=255,
            ),
        ),
    ]
