# Generated by Django 5.0.1 on 2024-03-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0047_alter_attendanceregister_status"),
        ("job", "0002_alter_job_age_alter_job_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="Age",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="department",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_deleted": False},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.department",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Experience"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="expired_date",
            field=models.DateField(
                blank=True,
                help_text="expired date",
                null=True,
                verbose_name="Expired Date",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Job Location"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="no_of_vacancies",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Number Of Vacancies",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_from",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Salary From"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary_to",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Salary To"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="start_date",
            field=models.DateField(
                blank=True, help_text="start date", null=True, verbose_name="Start Date"
            ),
        ),
    ]
