# Generated by Django 5.0.1 on 2024-03-14 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_alter_job_age_alter_job_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="Age",
            new_name="age",
        ),
    ]
