# Generated by Django 5.0.1 on 2024-03-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0004_rename_age_job_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
